name: Sync
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    name: Sync repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Checkout akiirui/domain-list-china
        uses: actions/checkout@v5
        with:
          repository: akiirui/domain-list-china
          path: mihomo
          ref: mihomo

      - name: Copy latest release
        run: |
          cp mihomo/* release/

      - name: Push to main
        continue-on-error: true
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "3736910+akiirui@users.noreply.github.com"
          git add release
          git commit -m "sync: $(date +%Y%m%d%H%M%S)"
          git push origin main
