name: Sync
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    name: Sync repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout akiirui/domain-list-china
        uses: actions/checkout@v4
        with:
          repository: akiirui/domain-list-china
          path: domain-list-china
          fetch-depth: 0

      - name: Set variables
        run: |
          cd domain-list-china
          echo "RELEASE_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Copy latest release
        run: |
          cp domain-list-china/release/mihomo/* release/

      - name: Push to main
        continue-on-error: true
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "3736910+akiirui@users.noreply.github.com"
          git add release
          git commit -m "${{ env.RELEASE_NAME }}"
          git push origin main

      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release/*.yaml,release/*.mrs"
          body: ${{ env.RELEASE_NAME }}
          name: ${{ env.RELEASE_NAME }}
          tag: ${{ env.RELEASE_NAME }}
